
DELIMITER $$
CREATE PROCEDURE FIND_ITEMS_LIKE(IN PARAM_ITEM_NAME VARCHAR(10), OUT PARAM_TOTAL BIGINT)
BEGIN
SELECT COUNT(*) INTO PARAM_TOTAL FROM ITEM WHERE NAME LIKE PARAM_ITEM_NAME;
END$$
DELIMITER ;